/** Generated by `scripts/build-golf-catalog.mjs` — do not edit. */

export interface UsCatalogEntry {
  n: string;
  la: number;
  lo: number;
  ci?: string;
  /** ISO country — US, CA, MX, … */
  co?: string;
  st?: string;
  /** Province / state when co !== US (BC, ON, QC, …) */
  pr?: string;
  o?: number;
  g?: string;
  h?: number;
  p?: number;
  y?: number;
  w?: string;
  sc?: Array<[number, number, number?]>;
  a?: "public" | "private" | "resort" | "unknown";
  /** Verified: location + par/holes + scorecard integrity */
  q?: 1;
  /** Shared facility id for sibling layouts at one address */
  fac?: string;
  /** regulation | executive | par3 | unknown */
  typ?: "regulation" | "executive" | "par3" | "unknown";
}

import catalogJson from './usCatalog.json';

export const US_CATALOG = catalogJson as UsCatalogEntry[];
export const US_CATALOG_VERIFIED = US_CATALOG.filter((entry) => entry.q === 1);
